public class ChunkOfWave {
  private double maximum = 0;
  private double minimum = 0;
  private double average = 0;

  private Processor wholeWave;

  public ChunkOfWave(String fileName) {
    wholeWave = new Processor(fileName);
  }
  /**
  * Calculates the average value, minimum value, and maximum of a segment of the double array.
  * The segments generated by this method are sliced apart
  * at even intervals. The "factor" parameter determines how often to split the file.
  */
  public void getInformation(int factor) {
    double[] oldWave = wholeWave.getOriginalSamples();
    int arrSizes = oldWave.length/factor; // the size of the arrays made
    double[] arr = new double[arrSizes];

    for(int i = 0; i < arrSizes; i++) {
      arr[i] = oldWave[i];
    }
    double sum = 0;
    for(int f = 0; f < arrSizes; f++) {
      sum += arr[f];
      if(arr[f] > maximum) {
        maximum = arr[f];
      }
      if(arr[f] < minimum) {
        minimum = arr[f];
      }
    }
    average = sum/arr.length;
    System.out.println("avg val: " + average);
    System.out.println("max val: " + maximum);
    System.out.println("min val: " + minimum);
  }
}
